In [1]:
import tensorflow as tf
import os
from riptide.binary.binary_funcs import *
from riptide.binary.binary_layers import Config
from riptide.binary.models.q_cifar_resnet import cifar_resnet20_v1
#tf.enable_eager_execution()

In [2]:
os.environ['CUDA_VISIBLE_DEVICES'] = ''

In [3]:
actQ = DQuantize
weightQ = XQuantize
config = Config(actQ=actQ, weightQ=weightQ, bits=2.0)
with config:
    model = cifar_resnet20_v1()

In [8]:
dummy_in = tf.keras.layers.Input(shape=[32,32,3], batch_size=1)
model(dummy_in)

<DeferredTensor 'None' shape=(1, 10) dtype=float32>

In [5]:
model.load_weights('/data/jwfromm/models/MAX_BINARY_confirm/model.ckpt-60000')

Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.


In [17]:
get_quantize_bits(model.layers[1].layers[0].weights[0])

(<tf.Tensor: id=1767, shape=(1, 1, 1, 16), dtype=float32, numpy=
 array([[[[0.0625    , 0.125     , 0.0625    , 0.0625    , 0.0625    ,
           0.0625    , 0.0625    , 0.0625    , 0.00097656, 0.0625    ,
           0.0625    , 0.03125   , 0.0625    , 0.0625    , 0.0625    ,
           0.0625    ]]]], dtype=float32)>,
 <tf.Tensor: id=1754, shape=(3, 3, 16, 16), dtype=float32, numpy=
 array([[[[ 1.,  1., -1., ..., -1., -1.,  1.],
          [-1., -1., -1., ...,  1.,  1.,  1.],
          [-1., -1.,  1., ..., -1.,  1.,  1.],
          ...,
          [-1., -1., -1., ..., -1.,  1., -1.],
          [ 1., -1., -1., ...,  1., -1., -1.],
          [ 1., -1., -1., ..., -1., -1.,  1.]],
 
         [[ 1., -1., -1., ..., -1.,  1., -1.],
          [-1., -1., -1., ...,  1.,  1., -1.],
          [ 1.,  1.,  1., ...,  1., -1., -1.],
          ...,
          [-1.,  1., -1., ..., -1.,  1., -1.],
          [ 1., -1., -1., ..., -1.,  1.,  1.],
          [-1., -1., -1., ..., -1.,  1.,  1.]],
 
         [[ 

In [7]:
get_quantize_bits(model.layers[-2].weights[0])

(<tf.Tensor: id=1732, shape=(1, 10), dtype=float32, numpy=
 array([[0.125, 0.25 , 0.25 , 0.125, 0.25 , 0.125, 0.25 , 0.25 , 0.25 ,
         0.25 ]], dtype=float32)>,
 <tf.Tensor: id=1719, shape=(64, 10), dtype=float32, numpy=
 array([[-1.,  1., -1., -1.,  1., -1.,  1., -1., -1., -1.],
        [ 1., -1., -1.,  1., -1.,  1., -1.,  1., -1., -1.],
        [-1., -1., -1., -1.,  1., -1., -1.,  1., -1.,  1.],
        [ 1., -1.,  1., -1., -1., -1.,  1., -1., -1., -1.],
        [ 1.,  1., -1., -1.,  1., -1., -1., -1., -1.,  1.],
        [-1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1.],
        [ 1.,  1., -1., -1., -1., -1., -1., -1.,  1., -1.],
        [ 1.,  1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1.],
        [-1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1., -1.],
        [-1.,  1.,  1., -1., -1., -1., -1., -1., -1.,  1.],
        [-1.,  1., -1., -1., -1.,  1.,  1., -1., -1., -1.],
        [ 1., -1.,  1., -1.,  1., -1., -1., -1.,  1., 